const API_URL='https://calm-sunset-b06e.matkosmo27.workers.dev';
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
async function api(path,opts={}){const token=localStorage.getItem('5d_token');opts.headers={'Content-Type':'application/json',...(opts.headers||{})};if(token)opts.headers.Authorization=`Bearer ${token}`;const r=await fetch(API_URL+path,opts);let d={};try{d=await r.json()}catch{}if(!r.ok||d.success===false)throw new Error(d.error||'Błąd API');return d}
function nav(){const file=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('[data-nav]').forEach(a=>{if(a.getAttribute('href')===file)a.classList.add('active')})}
function renderNav(){const n=$('[data-nav-root]');if(!n)return;n.innerHTML=`<nav class="nav"><div class="container nav-inner"><a class="brand" href="index.html"><img src="assets/logo.png" onerror="this.style.display='none'"><span>5<span>DRAGONS</span></span></a><div class="links"><a data-nav href="index.html">HOME</a><a data-nav href="team.html">TEAM</a><a data-nav href="academy.html">ACADEMY</a><a data-nav href="matches.html">MATCHES</a><a data-nav href="news.html">NEWS</a><a data-nav href="recruitment.html">RECRUITMENT</a><a data-nav href="about.html">ABOUT</a><a data-nav href="contact.html">CONTACT</a><a data-nav href="login.html">LOGIN</a></div><a class="btn" href="recruitment.html">JOIN US</a></div></nav>`;nav()}
function footer(){const f=$('[data-footer]');if(f)f.innerHTML=`<footer class="footer"><div class="container">© ${new Date().getFullYear()} 5DRAGONS Academy. All rights reserved.</div></footer>`}
async function loadPlayers(){const box=$('[data-players]');if(!box)return;try{const d=await api('/api/players');box.innerHTML=d.data.length?d.data.map(p=>`<div class="card"><div class="player"><img class="avatar" src="${p.avatar||'assets/logo.png'}"><div><h3>${p.nickname||p.name}</h3><span class="tag">${p.role||'Player'}</span><div class="muted">${p.team||'Main'}</div></div></div><div class="stats"><div class="stat"><strong>${p.kd||0}</strong><small>K/D</small></div><div class="stat"><strong>${p.adr||0}</strong><small>ADR</small></div><div class="stat"><strong>${p.elo||0}</strong><small>ELO</small></div><div class="stat"><strong>${p.level||0}</strong><small>FACEIT</small></div></div></div>`).join(''):'<p class="muted">Brak zawodników.</p>'}catch(e){box.innerHTML=`<p class="muted">${e.message}</p>`}}
async function loadNews(){const box=$('[data-news]');if(!box)return;try{const d=await api('/api/news');box.innerHTML=d.data.map(n=>`<a class="card" href="article.html?id=${n.id}"><span class="tag">${n.category||'News'}</span><h3>${n.title}</h3><p>${n.excerpt||''}</p><small class="muted">${n.created_at||''}</small></a>`).join('')||'<p class="muted">Brak newsów.</p>'}catch(e){box.innerHTML=`<p class="muted">${e.message}</p>`}}
async function loadMatches(){const box=$('[data-matches]');if(!box)return;try{const d=await api('/api/matches');box.innerHTML=d.data.map(m=>`<div class="card"><span class="tag">${m.status||'upcoming'}</span><h3>5DRAGONS <span class="muted">vs</span> ${m.opponent}</h3><p>${m.event||''} · ${m.map||'TBA'}</p><strong>${m.score||'—'}</strong><div class="muted">${m.date||''} ${m.time||''}</div></div>`).join('')||'<p class="muted">Brak meczów.</p>'}catch(e){box.innerHTML=`<p class="muted">${e.message}</p>`}}
function recruitment(){const form=$('#recruitment-form');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const status=$('#form-status');const d=Object.fromEntries(new FormData(form).entries());delete d.agreement;d.faceit=Number(d.faceit);d.age=Number(d.age);status.textContent='Wysyłanie...';try{await api('/api/recruitment/applications',{method:'POST',body:JSON.stringify(d)});form.reset();status.textContent='Zgłoszenie zostało wysłane.'}catch(err){status.textContent=err.message}})}
function contact(){const form=$('#contact-form');if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const s=$('#form-status');const d=Object.fromEntries(new FormData(form).entries());s.textContent='Wysyłanie...';try{await api('/api/contact',{method:'POST',body:JSON.stringify(d)});form.reset();s.textContent='Wiadomość została wysłana.'}catch(err){s.textContent=err.message}})}
function auth(){const form=$('#login-form');if(form)form.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form).entries());try{const r=await api('/api/login',{method:'POST',body:JSON.stringify(d)});localStorage.setItem('5d_token',r.token);location.href='profile.html'}catch(err){$('#form-status').textContent=err.message}});const reg=$('#register-form');if(reg)reg.addEventListener('submit',async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(reg).entries());try{await api('/api/register',{method:'POST',body:JSON.stringify(d)});location.href='login.html'}catch(err){$('#form-status').textContent=err.message}})}
async function article(){const box=$('[data-article]');if(!box)return;try{const id=new URLSearchParams(location.search).get('id');const d=await api('/api/news');const n=d.data.find(x=>String(x.id)===String(id));if(!n){box.innerHTML='<p>Nie znaleziono artykułu.</p>';return}box.innerHTML=`<article class="article"><span class="tag">${n.category||'News'}</span><h1>${n.title}</h1><p class="muted">${n.created_at||''}</p>${n.image?`<img src="${n.image}">`:''}<div class="article-body">${(n.content||n.excerpt||'').replace(/\n/g,'<br>')}</div></article>`}catch(e){box.innerHTML=`<p>${e.message}</p>`}}
async function profile(){const box=$('[data-profile]');if(!box)return;try{const d=await api('/api/me');box.innerHTML=`<div class="card"><h2>${d.user.username}</h2><p>${d.user.email||''}</p><span class="tag">${d.user.role}</span></div>`}catch{box.innerHTML='<div class="notice">Nie jesteś zalogowany. <a href="login.html">Zaloguj się</a>.</div>'}}
document.addEventListener('DOMContentLoaded',()=>{renderNav();footer();loadPlayers();loadNews();loadMatches();recruitment();contact();auth();article();profile()});
